### ISSUE TITLE
/api/school/lecture

### ISSUE THREAD

**Issue by Werfmon** [ThredeX/profesio#119]
Při vracení přednášek by to chtělo specifikovat zda student už je přihlášen.

**Comment by JustScreaMy** [comment]
Tato změna má dvě možnosti
1. Vytvoření nového endpointu jen pro studenty
1. Změna endpointu na pouze pro studenty

Vyber si

**Comment by Werfmon** [comment]
Nový EP bych nevytvářel, je to zbytečné, výše uvedený EP je použit pouze v jednom případě, volil bych změnu stávajícího.
