### ISSUE TITLE
/api/faculty/student

### ISSUE THREAD

**Issue by Werfmon** [ThredeX/profesio#120]
metoda: GET

error - unhadleRejection: RangeError: Invalid time value

**Comment by JustScreaMy** [comment]
V jaké situaci tohle vyhazuje, jaké data se posílají když to tuto chybu vyhodí. Nemám křišťálovou kouli abych tyto informace věštil :P

**Comment by Werfmon** [comment]
Tuto chybu to vyhazuje při nesprávných časech, křišťálovou kouli sice nemáš, ale insomnii ano.
