### ISSUE TITLE
Databázový model

### ISSUE THREAD

**Issue by JustScreaMy** [ThredeX/profesio#17]
Model v repozitáři (přídán v #16)NEODPOVÍDÁ modelu co jsme připravovali, uživatel nemá mít v sobě Učitel_ID apod.. Prosím změnit ať můžu co nejdřívě pracovat

**Comment by JustScreaMy** [comment]
+ Administrator má v modelu atributu oprávnění. Proč?

**Comment by Werfmon** [comment]
Administrátor má oprávnění kvůli jeho oprávnění, zda si data bude moct prohlížet nebo i upravovat.

**Comment by JustScreaMy** [comment]
True = Upravovat i Prohlížet
False = Pouze prohlížet?
Jestli ano tak bych to prejmenoval na něco víc specifického

**Comment by Werfmon** [comment]
Ano, tak to mám na mysli, navrhuju readonly atribut, true = čtení, false = úprava

**Comment by JustScreaMy** [comment]
Není lepší atribut přejmenovat na can_edit?

**Comment by Werfmon** [comment]
Záleží, uznávám, že co se týká přehlednosti tak ano. Změním na can_edit.

**Comment by Werfmon** [comment]
> Model v repozitáři (přídán v #16)NEODPOVÍDÁ modelu co jsme připravovali, uživatel nemá mít v sobě Učitel_ID apod.. Prosím změnit ať můžu co nejdřívě pracovat

Opraveno
