### ISSUE TITLE
Student

### ISSUE THREAD

**Issue by Werfmon** [ThredeX/profesio#56]
Při vrácení informací v EP /users/info je potřeba, aby se u studenta vracel entry_year.

**Comment by JustScreaMy** [comment]
/users/info vrací pouze všechny uživatele, jestli chceš vracet pouze studenty tak na to bude zvlášť endpoint, teoreticky se může přidat endpoint který vrátí všechny studenty, učitele i administrátory ve formátu např:
```
{
  students: [Student, ...],
  teachers: [Teacher, ...],
  admins: [Administrator, ...]
}
```

**Comment by Werfmon** [comment]
Bylo by fajn je mít všechny v jednom poli jako to bylo teď jen user bude mít navíc hodnoty podle toho jaké je role.

**Comment by JustScreaMy** [comment]
nevím jak moc to bude možné realizovat
