### ISSUE TITLE
/school/timetable

### ISSUE THREAD

**Issue by Werfmon** [ThredeX/profesio#64]
* Method: POST

* Data:  pošle uzavření a zpřístupnění rozvrhů

* Administrator:  true

**Comment by Werfmon** [comment]
Je potřeba přepsat a přejmenovat route /school/timetableend

**Comment by JustScreaMy** [comment]
> Je potřeba přepsat a přejmenovat route /school/timetableend

Přejmenovat na co?

**Comment by Werfmon** [comment]
/school/timetable
